package com.oley.mobilpayment.receivemomessage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-20T15:18:37.521+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "CReceiveMOMessageService", 
                  wsdlLocation = "http://localhost/mobilePayment/ReceiveMOMessage?wsdl",
                  targetNamespace = "http://cservices.mikro-odeme.com.tr/mapping/generated") 
public class CReceiveMOMessageService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cservices.mikro-odeme.com.tr/mapping/generated", "CReceiveMOMessageService");
    public final static QName CReceiveMOMessageServiceSoap = new QName("http://cservices.mikro-odeme.com.tr/mapping/generated", "CReceiveMOMessageServiceSoap");
    public final static QName CReceiveMOMessageServiceSoap12 = new QName("http://cservices.mikro-odeme.com.tr/mapping/generated", "CReceiveMOMessageServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/mobilePayment/ReceiveMOMessage?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CReceiveMOMessageService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost/mobilePayment/ReceiveMOMessage?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CReceiveMOMessageService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CReceiveMOMessageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CReceiveMOMessageService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CReceiveMOMessageServiceSoap
     */
    @WebEndpoint(name = "CReceiveMOMessageServiceSoap")
    public CReceiveMOMessageServiceSoap getCReceiveMOMessageServiceSoap() {
        return super.getPort(CReceiveMOMessageServiceSoap, CReceiveMOMessageServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CReceiveMOMessageServiceSoap
     */
    @WebEndpoint(name = "CReceiveMOMessageServiceSoap")
    public CReceiveMOMessageServiceSoap getCReceiveMOMessageServiceSoap(WebServiceFeature... features) {
        return super.getPort(CReceiveMOMessageServiceSoap, CReceiveMOMessageServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns CReceiveMOMessageServiceSoap
     */
    @WebEndpoint(name = "CReceiveMOMessageServiceSoap12")
    public CReceiveMOMessageServiceSoap getCReceiveMOMessageServiceSoap12() {
        return super.getPort(CReceiveMOMessageServiceSoap12, CReceiveMOMessageServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CReceiveMOMessageServiceSoap
     */
    @WebEndpoint(name = "CReceiveMOMessageServiceSoap12")
    public CReceiveMOMessageServiceSoap getCReceiveMOMessageServiceSoap12(WebServiceFeature... features) {
        return super.getPort(CReceiveMOMessageServiceSoap12, CReceiveMOMessageServiceSoap.class, features);
    }

}
