
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.oley.mobilpayment.receivemomessage;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-20T15:18:37.493+03:00
 * Generated source version: 2.6.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "CReceiveMOMessageService",
                      portName = "CReceiveMOMessageServiceSoap12",
                      targetNamespace = "http://cservices.mikro-odeme.com.tr/mapping/generated",
                      wsdlLocation = "http://localhost/mobilePayment/ReceiveMOMessage?wsdl",
                      endpointInterface = "com.oley.mobilpayment.receivemomessage.CReceiveMOMessageServiceSoap")
                      
public class CReceiveMOMessageServiceSoapImpl1 implements CReceiveMOMessageServiceSoap {

    private static final Logger LOG = Logger.getLogger(CReceiveMOMessageServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.oley.mobilpayment.receivemomessage.CReceiveMOMessageServiceSoap#receiveMOMessage(com.oley.mobilpayment.receivemomessage.CReceiveMOMessageInput  ınput )*
     */
    public com.oley.mobilpayment.receivemomessage.CReceiveMOMessageOutput receiveMOMessage(CReceiveMOMessageInput Input) { 
        LOG.info("Executing operation receiveMOMessage");
        System.out.println(Input);
        try {
            com.oley.mobilpayment.receivemomessage.CReceiveMOMessageOutput _return = new com.oley.mobilpayment.receivemomessage.CReceiveMOMessageOutput();
            _return.setStatusCode(-1917833538);
            _return.setErrorCode("ErrorCode-1435767978");
            _return.setErrorMessage("ErrorMessage880761200");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
