
package com.oley.mobilpayment.receivemomessage;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-20T15:18:37.517+03:00
 * Generated source version: 2.6.1
 * 
 */
 
public class CReceiveMOMessageServiceSoap_CReceiveMOMessageServiceSoap12_Server{

    protected CReceiveMOMessageServiceSoap_CReceiveMOMessageServiceSoap12_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CReceiveMOMessageServiceSoapImpl();
        String address = "http://localhost/mobilePayment/ReceiveMOMessag";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CReceiveMOMessageServiceSoap_CReceiveMOMessageServiceSoap12_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
