package com.oley.mobilpayment.receivemomessage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-20T15:18:37.504+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://cservices.mikro-odeme.com.tr/mapping/generated", name = "CReceiveMOMessageServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CReceiveMOMessageServiceSoap {

    @WebResult(name = "CReceiveMOMessageOutput", targetNamespace = "http://cservices.mikro-odeme.com.tr/mapping/generated", partName = "ReceiveMOMessageResult")
    @WebMethod(operationName = "ReceiveMOMessage", action = "http://oley.com/mobilePayment/CReceiveMOMessageService")
    public CReceiveMOMessageOutput receiveMOMessage(
        @WebParam(partName = "input", name = "input", targetNamespace = "http://cservices.mikro-odeme.com.tr/mapping/generated")
        CReceiveMOMessageInput Input
    );
}
