package com.mikro_odeme.services.sale;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-27T16:43:01.414+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "MSaleService", 
                  wsdlLocation = "http://vas.mikro-odeme.com/services/msaleservice.asmx?WSDL",
                  targetNamespace = "http://services.mikro-odeme.com/") 
public class MSaleService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.mikro-odeme.com/", "MSaleService");
    public final static QName MSaleServiceSoap12 = new QName("http://services.mikro-odeme.com/", "MSaleServiceSoap12");
    public final static QName MSaleServiceSoap = new QName("http://services.mikro-odeme.com/", "MSaleServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://vas.mikro-odeme.com/services/msaleservice.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MSaleService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://vas.mikro-odeme.com/services/msaleservice.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public MSaleService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MSaleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MSaleService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns MSaleServiceSoap
     */
    @WebEndpoint(name = "MSaleServiceSoap12")
    public MSaleServiceSoap getMSaleServiceSoap12() {
        return super.getPort(MSaleServiceSoap12, MSaleServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MSaleServiceSoap
     */
    @WebEndpoint(name = "MSaleServiceSoap12")
    public MSaleServiceSoap getMSaleServiceSoap12(WebServiceFeature... features) {
        return super.getPort(MSaleServiceSoap12, MSaleServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns MSaleServiceSoap
     */
    @WebEndpoint(name = "MSaleServiceSoap")
    public MSaleServiceSoap getMSaleServiceSoap() {
        return super.getPort(MSaleServiceSoap, MSaleServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MSaleServiceSoap
     */
    @WebEndpoint(name = "MSaleServiceSoap")
    public MSaleServiceSoap getMSaleServiceSoap(WebServiceFeature... features) {
        return super.getPort(MSaleServiceSoap, MSaleServiceSoap.class, features);
    }

}
