package com.mikro_odeme.services.sale;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-27T16:43:01.351+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://services.mikro-odeme.com/", name = "MSaleServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface MSaleServiceSoap {

    @WebResult(name = "CreditCardProxyResult", targetNamespace = "http://services.mikro-odeme.com/")
    @RequestWrapper(localName = "CreditCardProxy", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.CreditCardProxy")
    @WebMethod(operationName = "CreditCardProxy", action = "http://services.mikro-odeme.com/CreditCardProxy")
    @ResponseWrapper(localName = "CreditCardProxyResponse", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.CreditCardProxyResponse")
    public com.mikro_odeme.services.sale.MSaleOutput creditCardProxy(
        @WebParam(name = "token", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.sale.MAuthToken token,
        @WebParam(name = "input", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.sale.CreditCardProxyInput Input
    );

    @WebResult(name = "GetBokuPricePointsResult", targetNamespace = "http://services.mikro-odeme.com/")
    @RequestWrapper(localName = "GetBokuPricePoints", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.GetBokuPricePoints")
    @WebMethod(operationName = "GetBokuPricePoints", action = "http://services.mikro-odeme.com/GetBokuPricePoints")
    @ResponseWrapper(localName = "GetBokuPricePointsResponse", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.GetBokuPricePointsResponse")
    public java.lang.String getBokuPricePoints(
        @WebParam(name = "country", targetNamespace = "http://services.mikro-odeme.com/")
        java.lang.String country
    );

    @WebResult(name = "SaleWithConfirmResult", targetNamespace = "http://services.mikro-odeme.com/")
    @RequestWrapper(localName = "SaleWithConfirm", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.SaleWithConfirm")
    @WebMethod(operationName = "SaleWithConfirm", action = "http://services.mikro-odeme.com/SaleWithConfirm")
    @ResponseWrapper(localName = "SaleWithConfirmResponse", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.SaleWithConfirmResponse")
    public com.mikro_odeme.services.sale.MSaleOutput saleWithConfirm(
        @WebParam(name = "token", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.sale.MAuthToken token,
        @WebParam(name = "input", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.sale.MSaleInput Input
    );

    @WebResult(name = "GetSaleResult2Result", targetNamespace = "http://services.mikro-odeme.com/")
    @RequestWrapper(localName = "GetSaleResult2", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.GetSaleResult2")
    @WebMethod(operationName = "GetSaleResult2", action = "http://services.mikro-odeme.com/GetSaleResult2")
    @ResponseWrapper(localName = "GetSaleResult2Response", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.GetSaleResult2Response")
    public com.mikro_odeme.services.sale.MSaleResult getSaleResult2(
        @WebParam(name = "token", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.sale.MAuthToken token,
        @WebParam(name = "orderId", targetNamespace = "http://services.mikro-odeme.com/")
        java.lang.String orderId
    );

    @WebResult(name = "SaleWithoutConfirmResult", targetNamespace = "http://services.mikro-odeme.com/")
    @RequestWrapper(localName = "SaleWithoutConfirm", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.SaleWithoutConfirm")
    @WebMethod(operationName = "SaleWithoutConfirm", action = "http://services.mikro-odeme.com/SaleWithoutConfirm")
    @ResponseWrapper(localName = "SaleWithoutConfirmResponse", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.SaleWithoutConfirmResponse")
    public com.mikro_odeme.services.sale.MSaleOutput saleWithoutConfirm(
        @WebParam(name = "token", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.sale.MAuthToken token,
        @WebParam(name = "input", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.sale.MSaleInput Input
    );

    @WebResult(name = "GetSaleResultResult", targetNamespace = "http://services.mikro-odeme.com/")
    @RequestWrapper(localName = "GetSaleResult", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.GetSaleResult")
    @WebMethod(operationName = "GetSaleResult", action = "http://services.mikro-odeme.com/GetSaleResult")
    @ResponseWrapper(localName = "GetSaleResultResponse", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.GetSaleResultResponse")
    public com.mikro_odeme.services.sale.MSaleOutput getSaleResult(
        @WebParam(name = "token", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.sale.MAuthToken token,
        @WebParam(name = "orderId", targetNamespace = "http://services.mikro-odeme.com/")
        java.lang.String orderId
    );

    @WebResult(name = "SaleWithoutConfirmTestResult", targetNamespace = "http://services.mikro-odeme.com/")
    @RequestWrapper(localName = "SaleWithoutConfirmTest", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.SaleWithoutConfirmTest")
    @WebMethod(operationName = "SaleWithoutConfirmTest", action = "http://services.mikro-odeme.com/SaleWithoutConfirmTest")
    @ResponseWrapper(localName = "SaleWithoutConfirmTestResponse", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.SaleWithoutConfirmTestResponse")
    public com.mikro_odeme.services.sale.MSaleOutput saleWithoutConfirmTest(
        @WebParam(name = "token", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.sale.MAuthToken token,
        @WebParam(name = "input", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.sale.MSaleInput Input
    );

    @WebResult(name = "CancelTicketResult", targetNamespace = "http://services.mikro-odeme.com/")
    @RequestWrapper(localName = "CancelTicket", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.CancelTicket")
    @WebMethod(operationName = "CancelTicket", action = "http://services.mikro-odeme.com/CancelTicket")
    @ResponseWrapper(localName = "CancelTicketResponse", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.CancelTicketResponse")
    public com.mikro_odeme.services.sale.MResult cancelTicket(
        @WebParam(name = "token", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.sale.MAuthToken token,
        @WebParam(name = "ticketObjectId", targetNamespace = "http://services.mikro-odeme.com/")
        java.lang.String ticketObjectId
    );

    @WebResult(name = "QueryMicroPaymentsResult", targetNamespace = "http://services.mikro-odeme.com/")
    @RequestWrapper(localName = "QueryMicroPayments", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.QueryMicroPayments")
    @WebMethod(operationName = "QueryMicroPayments", action = "http://services.mikro-odeme.com/QueryMicroPayments")
    @ResponseWrapper(localName = "QueryMicroPaymentsResponse", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.QueryMicroPaymentsResponse")
    public com.mikro_odeme.services.sale.MQueryOutput queryMicroPayments(
        @WebParam(name = "token", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.sale.MAuthToken token,
        @WebParam(name = "input", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.sale.MQueryInput Input
    );

    @WebResult(name = "CheckTicketResult", targetNamespace = "http://services.mikro-odeme.com/")
    @RequestWrapper(localName = "CheckTicket", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.CheckTicket")
    @WebMethod(operationName = "CheckTicket", action = "http://services.mikro-odeme.com/CheckTicket")
    @ResponseWrapper(localName = "CheckTicketResponse", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.CheckTicketResponse")
    public com.mikro_odeme.services.sale.MResult checkTicket(
        @WebParam(name = "token", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.sale.MAuthToken token,
        @WebParam(name = "ticketObjectId", targetNamespace = "http://services.mikro-odeme.com/")
        java.lang.String ticketObjectId
    );

    @WebResult(name = "SaleWithTicketResult", targetNamespace = "http://services.mikro-odeme.com/")
    @RequestWrapper(localName = "SaleWithTicket", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.SaleWithTicket")
    @WebMethod(operationName = "SaleWithTicket", action = "http://services.mikro-odeme.com/SaleWithTicket")
    @ResponseWrapper(localName = "SaleWithTicketResponse", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.sale.SaleWithTicketResponse")
    public com.mikro_odeme.services.sale.MSaleTicketOutput saleWithTicket(
        @WebParam(name = "token", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.sale.MAuthToken token,
        @WebParam(name = "input", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.sale.MSaleTicketInput Input
    );
}
