package com.mikro_odeme.services.send_sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-27T16:47:27.272+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://services.mikro-odeme.com/", name = "MSendSMSServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface MSendSMSServiceSoap {

    @WebResult(name = "SendSMSResult", targetNamespace = "http://services.mikro-odeme.com/")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.send_sms.SendSMS")
    @WebMethod(operationName = "SendSMS", action = "http://services.mikro-odeme.com/SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://services.mikro-odeme.com/", className = "com.mikro_odeme.services.send_sms.SendSMSResponse")
    public com.mikro_odeme.services.send_sms.MSendSMSOutput sendSMS(
        @WebParam(name = "token", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.send_sms.MAuthToken token,
        @WebParam(name = "input", targetNamespace = "http://services.mikro-odeme.com/")
        com.mikro_odeme.services.send_sms.MSendSMSInput Input
    );
}
